mitm:
  host: 127.0.0.1
  port: 8080

webdriver:
  headless: False
  use: chrome
  edge:
    bin: msedgedriver.exe
  chrome:
    bin: ~/setup/chrome/chromedriver/chromedriver
    no_sandbox: True

output:
  use:
    - xml
    - debug
  xml:
    save_path: "/Users/blaketang/Movies/刘平直播11月/others/"
    file_pattern: "{room_id}_{ts}.xml"
  debug:
    save_path:
      error: "/Users/blaketang/Movies/刘平直播11月/others/error"
      unknown: "/Users/blaketang/Movies/刘平直播11月/others/debug"
      known: False

live:
  rooms:
    - ""
  users:
    - "MS4wLjABAAAAqqJWUXfl14OZztg_Ixn9g2vtI4RsKZzTagl6bOjyL20"

api:
  userinfo: 'https://live.douyin.com/webcast/user/?aid=6383&target_uid='
