mitm:
  host: 127.0.0.1
  port: 8080

webdriver:
  headless: False
  use: chrome
  edge:
    bin: msedgedriver.exe
  chrome:
    bin: /Users/blaketang/setup/chrome/chromedriver/chromedriver
    no_sandbox: True

output:
  use:
    - print
    - xml
    - debug
  xml:
    save_path: "./"
    file_pattern: "{room_id}_{ts}.xml"
  debug:
    save_path:
      error: "./error"
      unknown: "./debug"
      known: False

live:
  rooms:
    - "977133347170"
  users:
    - ""

api:
  userinfo: 'https://live.douyin.com/webcast/user/?aid=6383&target_uid='
